# cov2.sub 
container_image = osdf:///chtc/staging/e/egurney2/train.sif

executable = cov2.sh
arguments = $(job_num) $(dgp) $(n_sims) $(n_obs) $(n_covs) $(b_xy) $(b_cy) $(b_cx) $(r_cc) $(e_x) $(e_cov)

log = $(Cluster).log
error = error/error_$(job_num).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_output_remaps = "results_$(job_num).csv = results/results_$(job_num).csv"
on_exit_hold = exitcode != 0
max_retries = 1
transfer_input_files = train.sif, fun_cov2.R, fit_cov2.R, jobs.csv
materialize_max_idle = 1000
request_cpus = 1
request_memory = 2000MB
request_disk = 1000MB
want_campus_pools = true
want_ospool = true

queue job_num dgp n_sims n_obs n_covs b_xy b_cy b_cx r_cc e_x e_cov from jobs.csv